config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get "sign_up" => "users#new", :as => "sign_up"

  resources :users

  get 'users/edit'
  
  root 'users#index'
  resources :employees
  resources :positions
  resources :employee_types
  resources :sales_groups
  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/employee_type.rb
class EmployeeType < ActiveRecord::Base
end

app/models/position.rb
class Position < ActiveRecord::Base
end

app/models/sales_group.rb
class SalesGroup < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	
	validates :username, presence: true, uniqueness: true

    validates :email, presence: true, uniqueness: true

    validates :password, presence: true, on: :create,

    length: { minimum: 5 },

    confirmation: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employee_types_controller.rb
class EmployeeTypesController < ApplicationController
	def index
		@employee_types = EmployeeTypes.all
	end
	def new
		@employee_type = EmployeeTypes.new 
	end
	def create
		@employee_type = EmployeeTypes.new(employee_type_params)
		if @employee_type.save
			redirect_to employee_types_path
		else
			redirect_to new_employee_type_path
		end
	end
	def edit
		@employee_type = EmployeeTypes.find(params[:id])
	end
	def update
		@employee_type = EmployeeTypes.find(params[:id])
		if @employee_type.update(employee_type_params)
		redirect_to employee_types_path
	else
		redirect_to new_employee_type_part
	end
end
	def destroy
		@employee_type = EmployeeTypes.find(params[:id])
		if @employee_type.destroy
		redirect_to employee_types_path
	else
		redirect_to new_employee_type_path
	end
end
private 
 	def employee_type_params
		params.require(:employee_type).permit(:employee_type_id , :employee_type_name, :code)
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def index
		@employees = Employee.all
	end
	def new
		@employee = Employee.new 
	end
	def create
		@employee = Employee.new(employee_params)
		if @employee.save
			redirect_to employees_path
		else
			redirect_to new_employee_path
		end
	end
	def edit
		@employee = Employee.find(params[:id])
	end
	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
		redirect_to employees_path
	else
		redirect_to new_employee_part
	end
end
	def destroy
		@employee = Employee.find(params[:id])
		if @employee.destroy
		redirect_to employees_path
	else
		redirect_to new_employee_path
	end
end
private 
 	def employee_params
		params.require(:employee).permit(:employee_id , :position_id,  :email, :fullname, :address, :birthdate, :joindate, :phone, :mobile, :employee_type_id, :sales_group_id)
	end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
	def index
		@positions = Position.all
	end
	def new
		@position = Position.new 
	end
	def create
		@position = Position.new(position_params)
		if @position.save
			redirect_to positions_path
		else
			redirect_to new_position_path
		end
	end
	def edit
		@position = Position.find(params[:id])
	end
	def update
		@position = Position.find(params[:id])
		if @position.update(position_params)
		redirect_to positions_path
	else
		redirect_to new_position_part
	end
end
	def destroy
		@position = Position.find(params[:id])
		if @position.destroy
		redirect_to positions_path
	else
		redirect_to new_position_path
	end
end
private 
 	def position_params
		params.require(:position).permit(:position_id , :description, :code)
	end
end

app/controllers/sales_groups_controller.rb
class SalesGroupsController < ApplicationController
	def index
		@sales_groups = SalesGroup.all
	end
	def new
		@sales_group = SalesGroup.new 
	end
	def create
		@sales_group = SalesGroup.new(sales_group_params)
		if @sales_group.save
			redirect_to sales_groups_path
		else
			redirect_to new_sales_group_path
		end
	end
	def edit
		@sales_group = SalesGroup.find(params[:id])
	end
	def update
		@sales_group = SalesGroup.find(params[:id])
		if @sales_group.update(sales_group_params)
		redirect_to sales_groups_path
	else
		redirect_to new_sales_group_part
	end
end
	def destroy
		@sales_group = SalesGroup.find(params[:id])
		if @sales_group.destroy
		redirect_to sales_groups_path
	else
		redirect_to new_sales_group_path
	end
end
private 
 	def sales_group_params
		params.require(:sales_group).permit(:sales_group_id , :sales_group_name, :sales_group_manager, :code)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  
  def create

        @user = User.new(params_user)

        if @user.save

            flash[:notice] = "Success Add Records"

            redirect_to root_url

        else

            flash[:error] = "data not valid"

            render "new"

        end

    end
def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		redirect_to users_path
	else
		redirect_to new_user_part
	end
end
	def destroy
		@user = User.find(params[:id])
		if @user.destroy
		redirect_to users_path
	else
		redirect_to new_user_path
	end
end
    
    private

        def params_user

            params.require(:user).permit(:username, :email, :password, :password_confirmation)

        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_types_helper.rb
module EmployeeTypesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/sales_groups_helper.rb
module SalesGroupsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/employee_types/_form.html.erb
<%= form_for @employee do |f| %>


<%= f.label :employee_type_id %>
<%= f.text_field :employee_type_id %>
</br>
<%= f.label :code %>
<%= f.text_field :code %>
</br>
<%= f.label :employee_type_name %>
<%= f.text_field :employee_type_name %>
</br>


<%= f.submit %>
<% end %>

app/views/employee_types/edit.html.erb
<% render 'form' %>

app/views/employee_types/index.html.erb
<%=link_to 'tambah data', new_employee_type_path %>
<br/>

<table border='1'>
	<thead>
	<tr>
	<td>employee_type_Type_id</td>
	<td>code</td>
	<td>employee_type_type_name</td>
	
	</tr>

	</thead>
	<tbody>
		<% if @employee_type_types.count == 0 %>
		<tr>
			<td colspan=4>tidak ada data yang terdaftar</td>
		</tr>

		<%else%>
		<% @employee_type_types.each do |employee_type| %>
		<tr>
			<td><%= employee_type.employee_type_id %></td>
			<td><%= employee_type.position_id %></td>
			<td><%= employee_type.email %> </td>
			<td><%= employee_type.fullname %> </td>
			<td><%= employee_type.address %></td>
			<td><%= employee_type.birthdate %></td>
			<td><%= employee_type.joindate %></td>
			<td><%= employee_type.phone %></td>
			<td><%= employee_type.mobile %></td>
			<td><%= employee_type.employee_type_type_id %></td>
			<td><%= employee_type.sales_group_id %></td>
			
			<td><%= link_to 'edit', edit_employee_type_path(employee_type.id)%></td><td>|<%=link_to 'delete',employee_type_path(employee_type.id),method: 'delete'%></td>
			</tr>
				
			<%end%>
		<%end%>	
	</tbody>

app/views/employee_types/new.html.erb
<%= form_for @employee_type do |f| %>


<%= f.label :employee_type_id %>
<%= f.text_field :employee_type_id %>
</br>
<%= f.label :code %>
<%= f.text_field :code %>
</br>
<%= f.label :employee_type_name %>
<%= f.text_field :employee_type_name %>
</br>


<%= f.submit %>
<% end %>

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>
<%= f.label :employee_id %>
<%= f.text_field :employee_id %>
</br>
<%= f.label :position_id %>
<%= f.text_field :position_id %>
</br>
<%= f.label :email %>
<%= f.text_field :email %>
</br>
<%= f.label :fullname %>
<%= f.text_field :fullname %>
</br>
<%= f.label :address %>
<%= f.text_field :address %>
</br>
<%= f.label :birthdate %>
<%= f.text_field :birthdate %>
</br>
<%= f.label :joindate %>
<%= f.text_field :joindate %>
</br>
<%= f.label :phone %>
<%= f.text_field :phone %>
</br>
<%= f.label :mobile %>
<%= f.text_field :mobile %>
</br>
<%= f.label :employee_type_id %>
<%= f.text_field :employee_type_id %>
</br>
<%= f.label :sales_group_id %>
<%= f.text_field :sales_group_id %>
</br>


<%= f.submit %>
<% end %>

app/views/employees/edit.html.erb
<% render 'form' %>

app/views/employees/index.html.erb
<%=link_to 'tambah data', new_employee_path %>
<br/>

<table border='1'>
	<thead>
	<tr>
	<td>employee_id</td>
	<td>position_id</td>
	<td>email</td>
	<td>fullname</td>
	<td>address</td>
	<td>birthdate</td>
	<td>joindate</td>
	<td>phone</td>
	<td>mobile</td>
	<td>employee_type_id</td>
	<td>sales_group_id</td>
	</tr>

	</thead>
	<tbody>
		<% if @employees.count == 0 %>
		<tr>
			<td colspan=4>tidak ada data yang terdaftar</td>
		</tr>

		<%else%>
		<% @employees.each do |employee| %>
		<tr>
			<td><%= employee.employee_id %></td>
			<td><%= employee.position_id %></td>
			<td><%= employee.email %> </td>
			<td><%= employee.fullname %> </td>
			<td><%= employee.address %></td>
			<td><%= employee.birthdate %></td>
			<td><%= employee.joindate %></td>
			<td><%= employee.phone %></td>
			<td><%= employee.mobile %></td>
			<td><%= employee.employee_type_id %></td>
			<td><%= employee.sales_group_id %></td>
			
			<td><%= link_to 'edit', edit_employee_path(employee.id)%></td><td>|<%=link_to 'delete',employee_path(employee.id),method: 'delete'%></td>
			</tr>
				
			<%end%>
		<%end%>	
	</tbody>

app/views/employees/new.html.erb
<%= form_for @employee do |f| %>
<%= f.label :employee_id %>
<%= f.text_field :employee_id %>
</br>
<%= f.label :position_id %>
<%= f.text_field :position_id %>
</br>
<%= f.label :email %>
<%= f.text_field :email %>
</br>
<%= f.label :fullname %>
<%= f.text_field :fullname %>
</br>
<%= f.label :address %>
<%= f.text_field :address %>
</br>
<%= f.label :birthdate %>
<%= f.text_field :birthdate %>
</br>
<%= f.label :joindate %>
<%= f.text_field :joindate %>
</br>
<%= f.label :phone %>
<%= f.text_field :phone %>
</br>
<%= f.label :mobile %>
<%= f.text_field :mobile %>
</br>
<%= f.label :employee_type_id %>
<%= f.text_field :employee_type_id %>
</br>
<%= f.label :sales_group_id %>
<%= f.text_field :sales_group_id %>
</br>


<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrainingRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/positions/_form.html.erb
<%= form_for @position do |f| %>

<%= f.label :position_id %>
<%= f.text_field :position_id %>
</br>
<%= f.label :description %>
<%= f.text_field :description %>
</br>
<%= f.label :code %>
<%= f.text_field :code %>
</br>
<%= f.submit %>
<% end %>

app/views/positions/edit.html.erb
<% render 'form' %>

app/views/positions/index.html.erb
<%=link_to 'tambah data', new_position_path %>
<br/>

<table border='1'>
	<thead>
	<tr>
	<td>position_id</td>
	<td>description</td>
	<td>code</td>
	
	</tr>

	</thead>
	<tbody>
		<% if @positions.count == 0 %>
		<tr>
			<td colspan=4>tidak ada data yang terdaftar</td>
		</tr>

		<%else%>
		<% @positions.each do |position| %>
		<tr>
			<td><%= position.position_id %></td>
			<td><%= position.description %></td>
			<td><%= position.code %> </td>
			
			<td><%= link_to 'edit', edit_position_path(position.id)%></td><td>|<%=link_to 'delete',position_path(position.id),method: 'delete'%></td>
			</tr>
				
			<%end%>
		<%end%>	
	</tbody>

app/views/positions/new.html.erb
<%= form_for @positions do |f| %>

<%= f.label :position_id %>
<%= f.text_field :position_id %>
</br>
<%= f.label :description %>
<%= f.text_field :description %>
</br>
<%= f.label :code %>
<%= f.text_field :code %>
</br>



<%= f.submit %>
<% end %>

app/views/sales_groups/_form.html.erb
<%= form_for @employee do |f| %>

<%= f.label :sales_group_id %>
<%= f.text_field :sales_group_id %>
</br>
<%= f.label :sales_group_name %>
<%= f.text_field :sales_group_name %>
</br>
<%= f.label :sales_group_manager %>
<%= f.text_field :sales_group_manager %>
</br>
<%= f.label :code %>
<%= f.text_field :code %>
</br>


<%= f.submit %>
<% end %>

app/views/sales_groups/edit.html.erb
<% render 'form' %>

app/views/sales_groups/index.html.erb
<%=link_to 'tambah data', new_sales_group_path %>
<br/>

<table border='1'>
	<thead>
	<tr>
	<td>sales_group_id</td>
	<td>sales_group_name</td>
	<td>sales_group_manager</td>
	<td>code</td>
	
	</tr>

	</thead>
	<tbody>
		<% if @sales_groups.count == 0 %>
		<tr>
			<td colspan=4>tidak ada data yang terdaftar</td>
		</tr>

		<%else%>
		<% @sales_groups.each do |sales_group| %>
		<tr>
			<td><%= sales_group.sales_group_id %></td>
			<td><%= sales_group.sales_group_name %></td>
			<td><%= sales_group.sales_group_manager %> </td>
			<td><%= sales_group.code %> </td>
			
			
			<td><%= link_to 'edit', edit_sales_group_path(sales_group.id)%></td><td>|<%=link_to 'delete',sales_group_path(sales_group.id),method: 'delete'%></td>
			</tr>
				
			<%end%>
		<%end%>	
	</tbody>

app/views/sales_groups/new.html.erb
<%= form_for @employee do |f| %>

<%= f.label :sales_group_id %>
<%= f.text_field :sales_group_id %>
</br>
<%= f.label :sales_group_name %>
<%= f.text_field :sales_group_name %>
</br>
<%= f.label :sales_group_manager %>
<%= f.text_field :sales_group_manager %>
</br>
<%= f.label :code %>
<%= f.text_field :code %>
</br>


<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<%=link_to 'tambah data', new_user_path %>
<br/>

<table border='1'>
	<thead>
	<tr>
	<td>username</td>
	<td>email</td>
	<td>password</td>
	<td>password confirmation</td>
	<td>action<td>
	</tr>

	</thead>
	<tbody>
		<% if @users.count == 0 %>
		<tr>
			<td colspan=4>tidak ada data yang terdaftar</td>
		</tr>

		<%else%>
		<% @users.each do |user| %>
		<tr>
			<td><%= user.username %></td>
			<td><%= user.email %></td>
			<td><%= user.password %> </td>
			<td><%= user.password_confirmation %> </td>
			<td><%= link_to 'edit', edit_user_path(user.id)%></td><td>|<%=link_to 'delete',user_path(user.id),method: 'delete'%></td>
			</tr>
				
			<%end%>
		<%end%>	
	</tbody>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= @user.errors[:username].first unless @user.errors[:username].blank? %>
</br>

<%= f.label :email %>
<%= f.text_field :email %>
<%= @user.errors[:email].first unless @user.errors[:email].blank? %>
</br>

<%= f.label :password %>
<%= f.text_field :password %>
<%= @user.errors[:password].first unless @user.errors[:password].blank? %>
</br>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= @user.errors[:password_confirmation].first unless @user.errors[:password_confirmation].blank? %>
</br>

<%= f.submit %>
<% end %>